name: create-post-preview
on:
  pull_request:
    branches:
      - master
    paths:
      - content/post/*.md
jobs:
  take-screenshot:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v1.0.0
      - name: Install Mage
        run: |
          export GOPATH=$(go env GOPATH)
          go get -u -d github.com/magefile/mage
          cd $GOPATH/src/github.com/magefile/mage
          go run bootstrap.go
        env:
          GOPATH: /home/runner/go
      - name: Run Mage
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH/bin
          $GOPATH/bin/mage publish
      - name: Commit preview images
        uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Add post preview
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    services:
      hugo:
        image: jojomi/hugo:0.69.0
        ports:
          - 1313:1313
        volumes:
          - ${{ github.workspace }}/:/src
        env:
          HUGO_WATCH: true
